"""
Weak-to-Strong Supervision Pipeline
DRAFT ALPHA — REQUIRES TESTING AND ITERATION

Multi-model verification: smaller "highly correct" model labels data,
larger model learns the reasoning behind why that data is correct.

Key Concept: Use a specialized weak teacher to verify data, then train strong student
Use Case: Haiku-3.5 (weak, fast, correct) verifies finance data → Opus-4 (strong) learns reasoning

This is how you "link up" different skills without losing accuracy.

Reference: OpenAI's "Weak-to-Strong Generalization" (Dec 2023)
Applied to domain-specific skill training.

SELF-CORRECTION BLOCK:
    What Could Break:
      1. Weak model not actually "correct" — introduces systematic errors
      2. Strong model "forgets" weak model's corrections during training
      3. Distribution mismatch — weak model trained on different data than strong model
    How to Test:
      pytest tests/test_weak_to_strong.py -v
    How to Fix:
      Validate weak model on held-out test set before using as teacher
      Use confidence-based filtering — only use high-confidence weak labels
      Ensure weak and strong models see same data distribution
"""

import json
from pathlib import Path
from dataclasses import dataclass, asdict
from datetime import datetime
from typing import Literal, Optional
import random


@dataclass
class WeakLabel:
    """A label generated by the weak (teacher) model."""
    data_id: str
    domain: str
    input_text: str
    weak_prediction: str
    weak_confidence: float
    reasoning: str        # why the weak model chose this label
    created_at: str


@dataclass
class StrongTrainingExample:
    """A training example for the strong (student) model."""
    example_id: str
    domain: str
    input_text: str
    weak_label: str
    weak_reasoning: str
    verified: bool       # did weak label pass validation?
    quality_score: float  # 0.0-1.0, based on weak confidence + validation
    created_at: str


@dataclass
class SupervisionStats:
    """Statistics from the weak-to-strong pipeline."""
    domain: str
    total_examples: int
    weak_labels_generated: int
    weak_labels_verified: int
    avg_weak_confidence: float
    avg_quality_score: float
    verification_rate: float


SUPERVISION_DIR = Path("databases/weak_to_strong")
SUPERVISION_DIR.mkdir(parents=True, exist_ok=True)


class WeakModel:
    """
    Simulates a weak but highly accurate model (e.g., Haiku-3.5, GPT-4-mini).

    In production: Replace with actual API calls to smaller model.
    For now: Uses rule-based heuristics + database lookup.
    """

    def __init__(self, domain: str, db_path: Path):
        self.domain = domain
        self.db_path = db_path
        self._load_domain_rules()

    def _load_domain_rules(self):
        """Load domain-specific validation rules."""
        # Simplified: in production, load from actual database
        self.rules = {
            "finance": {
                "pe_threshold": 30,
                "debt_threshold": 2.0,
                "roe_threshold": 0.15,
            },
            "cybersecurity": {
                "threat_keywords": ["exploit", "malware", "vulnerability"],
                "safe_keywords": ["update", "patch", "secure"],
            },
        }

    def label(self, input_text: str) -> WeakLabel:
        """
        Generate a label using the weak model.

        Returns prediction + reasoning + confidence.
        """
        if self.domain == "finance":
            return self._label_finance(input_text)
        elif self.domain == "cybersecurity":
            return self._label_cybersecurity(input_text)
        else:
            return self._label_generic(input_text)

    def _label_finance(self, input_text: str) -> WeakLabel:
        """Finance-specific weak labeling."""
        input_lower = input_text.lower()

        # Check for P/E ratio questions
        if "pe" in input_lower or "price" in input_lower:
            # Parse number if present
            import re
            numbers = re.findall(r'\d+\.?\d*', input_text)
            if numbers:
                pe_value = float(numbers[0])
                if pe_value > self.rules["finance"]["pe_threshold"]:
                    prediction = "overvalued"
                    reasoning = f"PE ratio {pe_value} exceeds threshold {self.rules['finance']['pe_threshold']}"
                    confidence = 0.85
                else:
                    prediction = "fairly_valued"
                    reasoning = f"PE ratio {pe_value} is below threshold"
                    confidence = 0.80
            else:
                prediction = "insufficient_data"
                reasoning = "No PE value found in input"
                confidence = 0.50
        else:
            prediction = "unknown"
            reasoning = "Query not related to known financial metrics"
            confidence = 0.30

        return WeakLabel(
            data_id=f"weak_{datetime.utcnow().strftime('%Y%m%d%H%M%S')}",
            domain=self.domain,
            input_text=input_text,
            weak_prediction=prediction,
            weak_confidence=confidence,
            reasoning=reasoning,
            created_at=datetime.utcnow().isoformat(),
        )

    def _label_cybersecurity(self, input_text: str) -> WeakLabel:
        """Cybersecurity-specific weak labeling."""
        input_lower = input_text.lower()

        threat_count = sum(1 for kw in self.rules["cybersecurity"]["threat_keywords"] if kw in input_lower)
        safe_count = sum(1 for kw in self.rules["cybersecurity"]["safe_keywords"] if kw in input_lower)

        if threat_count > safe_count:
            prediction = "threat"
            reasoning = f"Threat keywords detected: {threat_count}"
            confidence = min(0.6 + threat_count * 0.1, 0.95)
        elif safe_count > 0:
            prediction = "safe"
            reasoning = f"Safe keywords detected: {safe_count}"
            confidence = min(0.6 + safe_count * 0.1, 0.90)
        else:
            prediction = "unknown"
            reasoning = "No clear threat or safe indicators"
            confidence = 0.40

        return WeakLabel(
            data_id=f"weak_{datetime.utcnow().strftime('%Y%m%d%H%M%S')}",
            domain=self.domain,
            input_text=input_text,
            weak_prediction=prediction,
            weak_confidence=confidence,
            reasoning=reasoning,
            created_at=datetime.utcnow().isoformat(),
        )

    def _label_generic(self, input_text: str) -> WeakLabel:
        """Generic weak labeling for other domains."""
        return WeakLabel(
            data_id=f"weak_{datetime.utcnow().strftime('%Y%m%d%H%M%S')}",
            domain=self.domain,
            input_text=input_text,
            weak_prediction="unknown",
            weak_confidence=0.5,
            reasoning="Generic labeling - no domain rules",
            created_at=datetime.utcnow().isoformat(),
        )


class WeakLabelValidator:
    """
    Validates weak labels against ground truth database.

    Only high-confidence, verified weak labels are used for strong model training.
    """

    def __init__(self, db_path: Path):
        self.db_path = db_path

    def validate(self, weak_label: WeakLabel) -> dict:
        """
        Validate weak label against database.

        Returns: {"verified": bool, "quality_score": float, "note": str}
        """
        # Confidence threshold
        if weak_label.weak_confidence < 0.6:
            return {
                "verified": False,
                "quality_score": weak_label.weak_confidence * 0.5,
                "note": "Weak confidence below threshold (0.6)",
            }

        # Domain-specific validation
        if weak_label.domain == "finance":
            return self._validate_finance(weak_label)
        elif weak_label.domain == "cybersecurity":
            return self._validate_cybersecurity(weak_label)
        else:
            # Default: accept high-confidence labels
            if weak_label.weak_confidence > 0.75:
                return {
                    "verified": True,
                    "quality_score": weak_label.weak_confidence,
                    "note": "High confidence label accepted",
                }
            return {
                "verified": False,
                "quality_score": weak_label.weak_confidence,
                "note": "Insufficient domain-specific validation",
            }

    def _validate_finance(self, weak_label: WeakLabel) -> dict:
        """Finance-specific validation."""
        # Check if reasoning is sound
        if "threshold" in weak_label.reasoning or "ratio" in weak_label.reasoning:
            quality = min(weak_label.weak_confidence + 0.1, 0.99)
            return {
                "verified": True,
                "quality_score": quality,
                "note": "Finance reasoning validated",
            }
        return {
            "verified": False,
            "quality_score": weak_label.weak_confidence * 0.7,
            "note": "Finance reasoning unclear",
        }

    def _validate_cybersecurity(self, weak_label: WeakLabel) -> dict:
        """Cybersecurity-specific validation."""
        if "keyword" in weak_label.reasoning.lower():
            quality = weak_label.weak_confidence
            return {
                "verified": True,
                "quality_score": quality,
                "note": "Cybersecurity heuristic validated",
            }
        return {
            "verified": False,
            "quality_score": weak_label.weak_confidence * 0.6,
            "note": "Heuristic unclear",
        }


class WeakToStrongPipeline:
    """
    End-to-end pipeline: raw data → weak labels → validation → strong training set.
    """

    def __init__(self, domain: str, db_path: Path):
        self.domain = domain
        self.weak_model = WeakModel(domain, db_path)
        self.validator = WeakLabelValidator(db_path)
        self.training_examples: list[StrongTrainingExample] = []

    def process_batch(self, raw_inputs: list[str]) -> list[StrongTrainingExample]:
        """
        Process a batch of raw inputs through the pipeline.

        Steps:
        1. Generate weak labels
        2. Validate each label
        3. Create training examples for strong model (verified only)
        """
        examples = []

        for input_text in raw_inputs:
            # Step 1: Weak model labels
            weak_label = self.weak_model.label(input_text)

            # Step 2: Validate
            validation = self.validator.validate(weak_label)

            # Step 3: Create training example
            example = StrongTrainingExample(
                example_id=f"strong_{datetime.utcnow().strftime('%Y%m%d%H%M%S%f')}",
                domain=self.domain,
                input_text=input_text,
                weak_label=weak_label.weak_prediction,
                weak_reasoning=weak_label.reasoning,
                verified=validation["verified"],
                quality_score=validation["quality_score"],
                created_at=datetime.utcnow().isoformat(),
            )

            examples.append(example)
            self.training_examples.append(example)

        return examples

    def export_training_set(
        self,
        min_quality: float = 0.7,
        output_format: Literal["jsonl", "hf_dataset"] = "jsonl",
    ) -> Path:
        """
        Export verified training examples for strong model fine-tuning.

        min_quality: Only export examples above this quality threshold
        """
        # Filter by quality
        high_quality = [
            ex for ex in self.training_examples
            if ex.verified and ex.quality_score >= min_quality
        ]

        output_file = SUPERVISION_DIR / f"{self.domain}_strong_training.jsonl"

        with open(output_file, "w") as f:
            for ex in high_quality:
                # Format for fine-tuning: input + weak_reasoning → weak_label
                record = {
                    "input": ex.input_text,
                    "reasoning": ex.weak_reasoning,
                    "label": ex.weak_label,
                    "quality": ex.quality_score,
                }
                f.write(json.dumps(record) + "\n")

        print(f"Exported {len(high_quality)} / {len(self.training_examples)} examples to {output_file}")
        return output_file

    def get_stats(self) -> SupervisionStats:
        """Get pipeline statistics."""
        total = len(self.training_examples)
        verified = sum(1 for ex in self.training_examples if ex.verified)

        if total == 0:
            return SupervisionStats(
                domain=self.domain,
                total_examples=0,
                weak_labels_generated=0,
                weak_labels_verified=0,
                avg_weak_confidence=0.0,
                avg_quality_score=0.0,
                verification_rate=0.0,
            )

        avg_quality = sum(ex.quality_score for ex in self.training_examples) / total

        return SupervisionStats(
            domain=self.domain,
            total_examples=total,
            weak_labels_generated=total,
            weak_labels_verified=verified,
            avg_weak_confidence=0.0,  # would need to store weak_confidence separately
            avg_quality_score=avg_quality,
            verification_rate=verified / total,
        )


if __name__ == "__main__":
    # Example: Finance domain weak-to-strong pipeline
    pipeline = WeakToStrongPipeline("finance", db_path=Path("data"))

    sample_queries = [
        "Is AAPL overvalued with PE ratio of 35?",
        "What is the PE ratio for GOOGL?",
        "TSLA has PE of 25, is this good?",
        "Analyze the debt-to-equity ratio",
        "Should I invest in tech stocks?",
    ]

    print("Processing batch through weak-to-strong pipeline...")
    examples = pipeline.process_batch(sample_queries)

    print(f"\nGenerated {len(examples)} training examples")
    for i, ex in enumerate(examples, 1):
        status = "✓" if ex.verified else "✗"
        print(f"{status} Example {i}: {ex.input_text[:50]}...")
        print(f"   Label: {ex.weak_label} | Quality: {ex.quality_score:.2f} | Reasoning: {ex.weak_reasoning[:60]}")

    # Export high-quality examples
    output = pipeline.export_training_set(min_quality=0.7)

    # Stats
    stats = pipeline.get_stats()
    print(f"\nPipeline Statistics:")
    print(f"  Domain: {stats.domain}")
    print(f"  Total examples: {stats.total_examples}")
    print(f"  Verified: {stats.weak_labels_verified} ({stats.verification_rate:.1%})")
    print(f"  Avg quality: {stats.avg_quality_score:.2f}")
